### ISSUE TITLE
How to run this example?

### ISSUE THREAD

**Issue by Sogl** [Multicolour/multicolour-example#2]
Hi!

My steps:
1. I use postgres: `npm i sails-postgresql --save`
2. Line 69 in `config.js`: `development: require("sails-postgresql")` and comment line 14 in `app.js`
3. Change db and port in `config.js`
4. `npm start`. Output:
```
'undefined' not recognised. Not good, setting to .any()
Server running at: http://sogl.local:1811
```
What does the first line mean?
5. Output in browser:
```
{"errors":{"title":"Not Found","status":404}}
```

What next? I need to create models/blueprints the same as table names in DB?

I think this example need some test DB data :blush: 

Env:
node 4.2.1
npm 3.3.12
OS X 10.10.5

**Comment by davemackintosh** [comment]
Hey @Sogl, if you go to `http://sogl.local:1811/docs` you'll see the Swagger docs. I've got a seed module nearly ready to be published to help get started :) I'll publish it shortly.

**Comment by davemackintosh** [comment]
@Sogl 

There is now a seed module which will create random data and write to the DB in a "development" environment, see https://github.com/Multicolour/multicolour-example/blob/master/app.js#L14.

:boom:
