### ISSUE TITLE
error: column gadget.person does not exist

### ISSUE THREAD

**Issue by Sogl** [Multicolour/multicolour-example#3]
Hi!

With `GET http://localhost:1811/person/1/relationships/gadgets`:
```
{
  "errors": [
    {
      "id": "b9240119-a707-4a07-b8d5-84c7e58348f9",
      "detail": "[Error (E_UNKNOWN) Encountered an unexpected error] Details:  error: column gadget.person does not exist\n"
    }
  ]
}
```

Repo:
https://github.com/Sogl/mult-ex

Sql dump:
https://github.com/Sogl/mult-ex/blob/master/install.sql

**Comment by davemackintosh** [comment]
I can't recreate this at all. Works fine for me, can you please send versions of the modules you're by running `npm list --depth=0`. It's also worth noting that there was a release on Friday of `0.3.2` https://github.com/Multicolour/multicolour/issues/50
